# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e86fb9bf15bc10dc2864eae1859e5d9d7f1959a4ac11c31f9bd29a13d55ba7f4ad1ad6904a5586c1221e3fbf2cbacd0204dc80218d79eff25aeac8fc32e9c87

test:
  secret_key_base: 5465518824ebd1d1de329208d75e2c8c93267103cd17017387dda97fa52450e3c4e4b5d723bd71037ea3f2432b3f74b33db19d7a7d63a65140b92fb92fc24691

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
